package com.luming.model.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;



/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Nov 15 17:29:44 CST 2018.</p>
 *
 * @author POJOs.groovy
 */

@Table ( name ="tb_permission" )
@Entity
public class PermissionDO implements Serializable {


    private static final long serialVersionUID =  6201351490741433395L;

    @Column(name = "id" )
    @Id
    private Integer id;

    @Column(name = "name" )
    private String name;

    @Column(name = "description" )
    private String description;

    @Column(name = "url" )
    private String url;

    @Column(name = "pid" )
    private Integer pid;

    public void setId(Integer id){
        this.id = id;
    }

    public Integer getId(){
        return this.id;
    }

    public void setName(String name){
        this.name = name;
    }

    public String getName(){
        return this.name;
    }
    
    public String getDescription() {
        return description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public void setUrl(String url){
        this.url = url;
    }

    public String getUrl(){
        return this.url;
    }

    public void setPid(Integer pid){
        this.pid = pid;
    }

    public Integer getPid(){
        return this.pid;
    }


}
