package com.luming.model.pojo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;



/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Nov 15 17:33:06 CST 2018.</p>
 *
 * @author POJOs.groovy
 */

@Table ( name ="tb_role_permission" )
@Entity
public class RolePermissionDO implements Serializable {


    private static final long serialVersionUID =  3618840201932906949L;

    @Column(name = "id" )
    @Id
    private Integer id;

    @Column(name = "role_id" )
    private Integer roleId;

    @Column(name = "permission_id" )
    private Integer permissionId;

    public void setId(Integer id){
        this.id = id;
    }

    public Integer getId(){
        return this.id;
    }

    public void setRoleId(Integer roleId){
        this.roleId = roleId;
    }

    public Integer getRoleId(){
        return this.roleId;
    }

    public void setPermissionId(Integer permissionId){
        this.permissionId = permissionId;
    }

    public Integer getPermissionId(){
        return this.permissionId;
    }


}
